### ISSUE TITLE
DSA Problems on Greedy Algo.

### ISSUE THREAD

**Issue by AyushKumar55** [20sinkypriya/Leetcoding#8]

**Comment by AyushKumar55** [comment]
Hello @20sinkypriya ,
Please assign me this issue and allow me to add some problems on **Greedy Algo** in Java.
Also, do add the labels for **hacktoberfest**.

**Comment by 20sinkypriya** [comment]
I assigned you the issue, please feel free to contribute and add to the same.

**Comment by AyushKumar55** [comment]
Thanks!
I have raised a PR. Please check.
